#!/bin/sh

  concurrently \
  --kill-others-on-fail \
  --prefix "[{name}]" \
  --names "test,lint:fix,typecheck,build" \
  --prefix-colors "bgRed.bold.white,bgGreen.bold.white,bgBlue.bold.white,bgMagenta.bold.white" \
    "pnpm run test --watch=false" \
    "pnpm run lint:fix" \
    "pnpm run typecheck" \
    "pnpm run build"
